# Generated by Django 3.2.3 on 2021-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.FloatField()),
                ('floor_area', models.FloatField()),
                ('column_area', models.FloatField()),
                ('concrete_wall_areaNS', models.FloatField()),
                ('concrete_wall_areaEW', models.FloatField()),
                ('masonry_wall_areaNS', models.FloatField()),
                ('masonry_wall_areaEW', models.FloatField()),
                ('captive_column', models.BooleanField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
